Repository SWEET-DEVELOPERS/sweet-client, pull requests merged in 2024-03, with the labels that each got.

#462 [토너먼트] 스타일 수정
  public/svg/img_bg.svg
  src/assets/svg/ImgBg.tsx
  src/assets/svg/index.ts
  src/components/Tournament/Intro/TournamentIntroContatiner.style.tsx
  src/components/Tournament/TournamentFlow/TournamentFlowContainer.style.ts
  src/components/Tournament/TournamentFlow/TournamentFooter/TournamentFooter.style.ts
  src/components/Tournament/TournamentResult/TournamentResultCard/TournamentResultCard.style.ts
  src/components/common/Button/Next/BtnNext.tsx
Labels: style🎨, 토너먼트 🏆

#468 [공통] 이미지 최적화 라이브러리 설치
  package.json
  yarn.lock
Labels: chore🧹

#467 [선물등록, 선물 홈] 최종 QA 스타일 수정
  public/svg/gifthome_background.svg
  src/App.style.ts
  src/App.tsx
  src/assets/img/gifthome_background.webp
  src/assets/svg/GiftHomeBackground.tsx
  src/assets/svg/IcLeft.tsx
  src/assets/svg/index.ts
  src/components/GiftAdd/AddGiftLink/common/InputUrl/InputUrl.styled.ts
  src/components/GiftAdd/ItemTextField/ItemTextField.styled.ts
  src/components/GiftAdd/ItemTextField/ItemTextField.tsx
  src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.styled.ts
  src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.tsx
  src/pages/GiftHomeDetail/GiftHomeDetail.styled.ts
Labels: fix 🛠️, style🎨, 선물등록 🎁, 선물홈 🎁

#465 [온보딩] 최종qa 스타일 & step04 날짜 연속 수정 시 오류 해결 & 아이폰 공유하기 시 텍스트 같이 복사 해결
  src/components/OnBoardingSteps/Step02/Step02.style.ts
  src/components/OnBoardingSteps/Step02/Step02.tsx
  src/components/OnBoardingSteps/Step03/Step03.tsx
  src/components/OnBoardingSteps/Step04/Step04.tsx
  src/components/OnBoardingSteps/Step06/OnboardingFinalFooter.tsx
  src/hooks/common/useHandleShare.tsx
  src/hooks/onboarding/useTournamentScheduleCalendar.tsx
Labels: fix 🛠️, refactor ⚙️, style🎨

#480 [선물 등록] 이미지 url 파일 변환 실패 시 선물 등록 사항 초기화되도록 수정
  src/components/GiftAdd/AddGiftLayout/AddGiftWithoutLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx
  src/hooks/useConvertURLtoFile.tsx
Labels: fix 🛠️, 선물등록 🎁

#481 [선물홈, 선물등록] 이미지 최적화 진행
  src/assets/img/gifthome_background.webp
  src/components/GiftAdd/AddGiftFooter/AddGiftFooter.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithoutLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx
  src/components/GiftAdd/GiftAddButtons/GiftAddButtonsWrapper.styled.ts
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayout.tsx
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayoutHeader.style.ts
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayoutSkeleton.style.ts
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayoutSkeleton.tsx
  src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.styled.ts
  src/hooks/queries/etc/useBinarizeAndPutImage.tsx
  src/hooks/useHandleImageUpload.tsx
  src/pages/GiftAdd/GiftAddPage.tsx
  src/pages/GiftHomeDetail/GiftHomeDetail.tsx
  src/pages/GiftHomeDetail/GiftHomeDetail2030.tsx
  src/router/Router.tsx
  src/style/GlobalStyle.ts
Labels: refactor ⚙️, 선물등록 🎁, 선물홈 🎁

#471 [마이페이지,시작페이지] 최종 QA 반영입니다 !
  public/svg/tournament01.svg
  public/svg/tournament02.svg
  public/svg/tournament03.svg
  public/svg/tournament04.svg
  src/assets/svg/Tournament01.tsx
  src/assets/svg/Tournament02.tsx
  src/assets/svg/Tournament03.tsx
  src/assets/svg/Tournament04.tsx
  src/assets/svg/index.ts
  src/components/CardRoom/CardRoom.style.ts
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.style.ts
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.tsx
  src/pages/MyPage/Detail/DetailProgressRoom/DetailProgress.style.ts
  src/pages/Start/StartAnimation/TournamentAnimation/StartTournamentAnimation.style.ts
  src/pages/Start/StartAnimation/TournamentAnimation/StartTournamentAnimation.tsx
Labels: refactor ⚙️, style🎨, 마이페이지 👤, 시작페이지 📄

#484 [토너먼트] 결과 이미지 높이 지정 스타일
  src/components/Tournament/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.style.ts
  src/components/Tournament/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.tsx
  src/components/Tournament/TournamentResult/TournamentResultCard/TournamentResultCard.style.ts
Labels: 토너먼트 🏆

#483 [온보딩] step02 -> step03 넘어갈 때 스켈레톤 ui 적용
  src/components/OnBoardingSteps/Skeleton/Skeleton.style.ts
  src/components/OnBoardingSteps/Skeleton/Skeleton.tsx
  src/components/OnBoardingSteps/Step02/Step02.tsx
  src/components/OnBoardingSteps/Step05/Step05.tsx
  src/core/toast-messages.ts
Labels: feat💡, 온보딩 📝

#474 [마이페이지] 로그아웃 버튼 클릭 시 모달 나타내기
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayout.tsx
  src/components/common/Button/Logout/BtnLogout.tsx
  src/components/common/Modal/DeleteModal.tsx
  src/pages/MyPage/MyPage.tsx
Labels: feat💡, refactor ⚙️, 마이페이지 👤

#489 [시작페이지] 이미지 최적화 (webP로 형식 변환)
  src/assets/img/home_background.webp
  src/assets/img/main02.webp
  src/assets/img/main03.webp
  src/assets/img/main04.webp
  src/assets/img/main_02.webp
  src/assets/img/main_03.webp
  src/assets/img/main_04.webp
  src/pages/Start/Start.style.ts
Labels: refactor ⚙️, style🎨, 시작페이지 📄

#494 [시작페이지] 토너먼트 이미지 삭제 후 webp 변환
  src/assets/img/main03_no_animation.webp
  src/pages/Start/Start.style.ts
  src/pages/Start/Start.tsx
Labels: fix 🛠️, 시작페이지 📄

#492 refactor: heic 변환 처리 추가
  package.json
  src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx
  src/hooks/useHandleImageUpload.tsx
  yarn.lock
Labels: refactor ⚙️, 선물등록 🎁

#485 3/14 목 오후 11:21 기준 develop -> main
  package.json
  src/assets/img/Main02.png
  src/assets/img/Main03.png
  src/assets/img/Main04.png
  src/assets/img/Rectangle.png
  src/assets/img/home_background.webp
  src/assets/img/main02.webp
  src/assets/img/main03.webp
  src/assets/img/main03_no_animation.webp
  src/assets/img/main04.webp
  src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx
  src/components/OnBoardingSteps/Step04/TimePicker.tsx
  src/core/toast-messages.ts
  src/hooks/onboarding/useNameInput.tsx
  src/hooks/useHandleImageUpload.tsx
  src/pages/Start/Start.style.ts
  src/pages/Start/Start.tsx
  yarn.lock
Labels: fix 🛠️

#495 [온보딩] step05 라디오 버튼 테두리 짤려 보이는 현상 수정
  src/assets/svg/IcCircle.tsx
  src/assets/svg/IcCirclePink.tsx
  src/components/OnBoardingSteps/Step03/Step03.tsx
  src/components/common/Button/Radio/BtnRadio.tsx
Labels: style🎨, 온보딩 📝

#497 [온보딩] step02 썸네일 등록 시 아이폰 이미지 확장자(heic) 업로드 안되는 현상 수정
  src/components/OnBoardingSteps/Step02/Step02.tsx
  src/context/Onboarding/OnboardingContext.tsx
  src/hooks/common/usePreviewImage.tsx
  src/hooks/onboarding/useFormatDate.tsx
Labels: feat💡, refactor ⚙️, 온보딩 📝

#501 [마이페이지] 선물방으로 이동 버튼 기능 추가
  src/components/CardRoom/DoneCardRoom.tsx
  src/components/CardRoom/EditCardRoom.tsx
  src/components/CardRoom/ProgressCardRoom.tsx
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.style.ts
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.tsx
  src/pages/MyPage/Detail/DetailProgressRoom/DetailProgress.style.ts
  src/pages/MyPage/Detail/DetailProgressRoom/DetailProgressRoom.tsx
  src/pages/MyPage/Detail/EmptyView/EmptyView.style.ts
  src/pages/MyPage/Detail/EmptyView/EmptyView.tsx
Labels: fix 🛠️, refactor ⚙️, style🎨, 마이페이지 👤

#502 Develop에서 main merge / 마이페이지 버튼 기능 + tag 위치 반영
  src/assets/svg/IcCircle.tsx
  src/assets/svg/IcCirclePink.tsx
  src/components/CardRoom/DoneCardRoom.tsx
  src/components/CardRoom/EditCardRoom.tsx
  src/components/CardRoom/ProgressCardRoom.tsx
  src/components/OnBoardingSteps/Step02/Step02.tsx
  src/components/OnBoardingSteps/Step03/Step03.tsx
  src/components/common/Button/Radio/BtnRadio.tsx
  src/context/Onboarding/OnboardingContext.tsx
  src/hooks/common/usePreviewImage.tsx
  src/hooks/onboarding/useFormatDate.tsx
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.style.ts
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.tsx
  src/pages/MyPage/Detail/DetailProgressRoom/DetailProgress.style.ts
  src/pages/MyPage/Detail/DetailProgressRoom/DetailProgressRoom.tsx
  src/pages/MyPage/Detail/EmptyView/EmptyView.style.ts
  src/pages/MyPage/Detail/EmptyView/EmptyView.tsx
Labels: merge 🎯

#504 [시작페이지] 이미지 화질 수정
  src/assets/img/main02.webp
  src/assets/img/main03.webp
  src/assets/img/main03_no_animation.webp
  src/assets/img/main04.webp
  src/pages/Start/Start.style.ts
Labels: fix 🛠️

#511 [공통] vercel analytics, speed-insights 적용
  package.json
  src/App.tsx
  yarn.lock
Labels: chore🧹
