Repository SWEET-DEVELOPERS/sweet-client, pull requests merged in 2024-02, with the labels that each got.

#314 [리프레쉬 토큰] 리프레쉬 토큰 만료 시 재로그인
  src/apis/client.ts
Labels: fix

#316 [리프레쉬 토큰] 확인을 위한 console.log 작성
  src/apis/client.ts
Labels: fix

#325 Develop에서 main merge
  src/apis/client.ts
Labels: merge

#334 [로그인 유지 + refreshToken 재발급] 코드리뷰를 위한 pr
  src/apis/client.ts
Labels: fix 🛠️, refactor ⚙️

#341 [로컬로그인] production 모드와 development 모드 구분 하여 로그인 가능하도록
  src/apis/client.ts
  src/hooks/queries/tournament/useGetRanking.tsx
  src/pages/Start/Start.tsx
  src/utils/.keep
  src/utils/login.ts
Labels: feat💡, refactor ⚙️, API 🧬

#338 [시작페이지] 코드 관심사의 분리
  src/components/Footer/Footer.style.ts
  src/pages/Start/Start.style.ts
  src/pages/Start/Start.tsx
  src/pages/Start/StartAnimation/GiftAnimation/StartGiftAnimation.style.ts
  src/pages/Start/StartAnimation/GiftAnimation/StartGiftAnimation.tsx
  src/pages/Start/StartAnimation/ScrollAnimation/StartScrollAnimation.style.ts
  src/pages/Start/StartAnimation/ScrollAnimation/StartScrollAnimation.tsx
  src/pages/Start/StartButtonWithTokenCheck/StartButtonWithTokenCheck.style.ts
  src/pages/Start/StartButtonWithTokenCheck/StartButtonWithTokenCheck.tsx
  src/style/GlobalStyle.ts
  src/styles/.keep
Labels: refactor ⚙️, style🎨, 시작페이지 📄

#346 [상태관리] recoil 삭제
  package.json
  src/App.tsx
  src/recoil/atoms.ts
  yarn.lock
Labels: refactor ⚙️

#345 [로컬 로그인] 기존 닫힌 review를 위한 pr (링크 확인 부탁 드립니다.)
  src/apis/client.ts
Labels: fix 🛠️, refactor ⚙️

#339 [선물 등록, 선물방 편집] 리액트 쿼리 관련 데이터 실시간 업데이트 문제 해결
  src/components/GiftAdd/AddGiftFooter/AddGiftFooter.tsx
  src/components/GiftAdd/AddGiftLink/common/GiftAddNextBtn/GiftAddNextBtn.tsx
  src/components/GiftAdd/GiftAddPageBottomSection/GiftAddPageBottom.tsx
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayout.tsx
  src/hooks/queries/etc/usePostMyPresignedUrl.tsx
  src/hooks/queries/gift/useDeleteMyGift.tsx
  src/hooks/queries/gift/usePostGift.tsx
  src/hooks/queries/room/useDeleteRoomMember.tsx
  src/pages/MyPage/EditRoom/CardGuest/CardGuest.tsx
  src/pages/MyPage/EditRoom/EditRoom.tsx
  src/types/member/index.d.ts
Labels: fix 🛠️, feat💡, 선물등록 🎁, API 🧬, 선물방 편집 ✍️

#349 [로그인] 로그인 에러 페이지
  src/apis/client.ts
  src/components/GiftAdd/AddGiftFooter/AddGiftFooter.tsx
  src/pages/LoginError/LoginError.style.ts
  src/pages/LoginError/LoginError.tsx
  src/router/Router.tsx
Labels: feat💡

#347 [선물 등록] PresignedUrl로 선물 등록되도록 수정 & 커스텀 훅 분리
  src/components/GiftAdd/AddGiftFooter/AddGiftFooter.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithoutLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx
  src/components/GiftAdd/GiftAddButtons/GiftAddButtonsWrapper.tsx
  src/components/GiftHome/GiftHome2030Gifts/GiftHome2030Gifts.tsx
  src/components/common/MiniTimer/MiniTimer.tsx
  src/hooks/queries/etc/useBinarizeAndPutImage.tsx
  src/hooks/queries/etc/usePostMyPresignedUrl.tsx
  src/hooks/queries/etc/usePutMyPresignedUrl.tsx
  src/hooks/queries/gift/usePostGift.tsx
  src/hooks/queries/onboarding/usePutPresignedUrl.tsx
  src/hooks/useConvertURLtoFile.tsx
  src/hooks/useGetPresignedUrl.tsx
  src/hooks/useHandleImageUpload.tsx
  src/hooks/useParseFileName.tsx
  src/hooks/usePutImageUrlToS3.tsx
  src/pages/GiftAdd/GiftAddPage.tsx
Labels: fix 🛠️, feat💡, refactor ⚙️, 선물등록 🎁, 온보딩 📝, API 🧬

#343 온보딩 구조 context API로 변경 & 관심사 분리 & 공통 Title 변경
  src/components/OnBoardingSteps/Step01/Step01.style.ts
  src/components/OnBoardingSteps/Step01/Step01.tsx
  src/components/OnBoardingSteps/Step02/Step02.style.ts
  src/components/OnBoardingSteps/Step02/Step02.tsx
  src/components/OnBoardingSteps/Step03/Step03.style.ts
  src/components/OnBoardingSteps/Step03/Step03.tsx
  src/components/OnBoardingSteps/Step04/DatePicker.tsx
  src/components/OnBoardingSteps/Step04/Step04.style.ts
  src/components/OnBoardingSteps/Step04/Step04.tsx
  src/components/OnBoardingSteps/Step04/TimePicker.tsx
  src/components/OnBoardingSteps/Step05/SelectTimeOptions.tsx
  src/components/OnBoardingSteps/Step05/Step05.style.ts
  src/components/OnBoardingSteps/Step05/Step05.tsx
  src/components/OnBoardingSteps/Step06/Step06.style.ts
  src/components/OnBoardingSteps/Step06/Step06.tsx
  src/components/OnBoardingSteps/onboardingBtn/OnBoardingBtn.style.ts
  src/components/OnBoardingSteps/onboardingBtn/OnBoardingBtn.tsx
  src/components/common/Button/Radio/BtnRadio.tsx
  src/components/common/title/Title.tsx
  src/context/Onboarding/OnboardingContext.tsx
  src/hooks/common/usePreviewImage.tsx
  src/hooks/onboarding/useCalendarOpen.tsx
  src/hooks/onboarding/useFormatDate.tsx
  src/hooks/onboarding/useNameInput.tsx
  src/hooks/onboarding/useSetTournamentDuration.tsx
  src/hooks/onboarding/useTimerOpen.tsx
  src/hooks/queries/etc/usePostPresignedUrl.tsx
  src/hooks/queries/onboarding/useBinarizeAndPutImage.tsx
  src/hooks/queries/onboarding/useGetGifteeInfo.tsx
  src/hooks/queries/onboarding/usePutPresignedUrl.tsx
  src/pages/OnBoardingPage.tsx
  src/pages/Participants/ParticipantsView.style.ts
  src/pages/Participants/ParticipantsView.tsx
  src/router/Router.tsx
  src/types/Onboarding/index.ts
  src/utils/TimeOptionHelper.ts
Labels: refactor ⚙️, 선물등록 🎁, API 🧬

#350 [선물 등록] ContextApi 적용
  src/components/GiftAdd/AddGiftFooter/AddGiftFooter.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithoutLinkLayout.tsx
  src/components/GiftAdd/AddGiftLink/GiftAddFirstLinkLayout/GiftAddFirstLinkLayout.tsx
  src/components/GiftAdd/AddGiftLink/common/LinkAddHeader/LinkAddHeader.tsx
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayout.tsx
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayoutHeader.tsx
  src/context/AddGift/AddGiftContext.tsx
  src/pages/GiftAdd/GiftAddPage.tsx
  src/router/Router.tsx
  src/types/gift/index.d.ts
Labels: feat💡, refactor ⚙️, 선물등록 🎁

#354 [토너먼트] 중복자 예외처리 + 토너먼트 로직 분리
  src/components/Tournament/Intro/TournamentDeleteButton/TournamentDeleteButton.style.ts
  src/components/Tournament/Intro/TournamentDeleteButton/TournamentDeleteButton.tsx
  src/components/Tournament/Intro/TournamentIntroContainer.tsx
  src/components/Tournament/TournamentFlow/TournamentFlowContainer.tsx
  src/components/Tournament/TournamentFlow/TournamentFlowLogic.tsx
  src/hooks/queries/tournament/useGetItem.tsx
  src/hooks/tournament/useRandomItems.tsx
Labels: fix 🛠️, refactor ⚙️, 토너먼트 🏆, API 🧬

#370 [마이페이지] 코드 리펙토링
  src/components/common/Button/Logout/BtnLogout.tsx
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.tsx
  src/pages/MyPage/Detail/DetailProgressRoom/DetailProgressRoom.tsx
  src/pages/MyPage/EditRoom/EditRoom.tsx
  src/pages/MyPage/GiftRoomView/DoneGiftView/DoneGiftView.tsx
  src/pages/MyPage/GiftRoomView/GiftRoomHeader/GiftRoomHeader.tsx
  src/pages/MyPage/GiftRoomView/ProgressGiftView/ProgressGiftView.tsx
  src/pages/MyPage/MyPage.tsx
  src/types/member/index.d.ts
Labels: refactor ⚙️

#368 [favicon/og] 파비콘과 오픈그래프
  index.html
  public/apple-touch-icon.png
  public/favicon.ico
  public/thumbnail_image.png
Labels: feat💡

#372 Develop에서 main merge(코드 정리 반영 + 파비콘) + 리프레쉬 토큰 에러 경우 모든 경우 재로그인
  index.html
  public/apple-touch-icon.png
  public/favicon.ico
  public/thumbnail_image.png
  src/apis/client.ts
  src/components/common/Button/Logout/BtnLogout.tsx
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.tsx
  src/pages/MyPage/Detail/DetailProgressRoom/DetailProgressRoom.tsx
  src/pages/MyPage/EditRoom/EditRoom.tsx
  src/pages/MyPage/GiftRoomView/DoneGiftView/DoneGiftView.tsx
  src/pages/MyPage/GiftRoomView/GiftRoomHeader/GiftRoomHeader.tsx
  src/pages/MyPage/GiftRoomView/ProgressGiftView/ProgressGiftView.tsx
  src/pages/MyPage/MyPage.tsx
  src/types/member/index.d.ts
Labels: fix 🛠️, merge 🎯

#381 feat: 모바일에서 카카오 로그인 버튼 안보이는 현상 로직 수정
  src/pages/Participants/ParticipantsView.tsx
Labels: feat💡

#378 [1.5차 QA : 토너먼트] 토너먼트 방 종료 버튼 구현 및 중복 참여자 ui 개선
  src/components/Tournament/Intro/TournamentDeleteButton/TournamentDeleteButton.tsx
  src/components/Tournament/Intro/TournamentIntroContainer.tsx
Labels: feat💡, refactor ⚙️, 토너먼트 🏆

#393 [1.5차 QA] 선물 등록 완료 버튼 관련 버그 수정(기본 이미지 문제, 로딩 뷰 처리)
  src/components/GiftAdd/AddGiftFooter/AddGiftFooter.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithoutLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx
  src/components/GiftAdd/AddGiftLink/common/GiftAddBtnWrapper/GiftAddBtnWrapper.tsx
  src/components/GiftAdd/AddGiftLink/common/InputUrl/InputUrl.tsx
  src/context/AddGift/AddGiftContext.tsx
  src/hooks/queries/gift/usePostGift.tsx
  src/hooks/useConvertURLtoFile.tsx
  src/pages/GiftAdd/GiftAddPage.tsx
Labels: fix 🛠️, refactor ⚙️, 선물등록 🎁

#403 [1.5차] 선물등록 스타일 QA
  src/components/GiftAdd/AddGiftFooter/AddGiftFooter.styled.ts
  src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.styled.ts
  src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx
  src/components/GiftAdd/AddGiftLayout/common/WriteItemInfo/WithoutLinkWriteItemInfo.tsx
  src/components/GiftAdd/AddGiftLink/common/GiftAddNextBtn/GiftAddNextBtn.styled.ts
  src/components/GiftAdd/AddGiftLink/common/InputUrl/InputUrl.styled.ts
  src/components/GiftAdd/AddGiftLink/common/InputUrl/InputUrl.tsx
  src/components/GiftAdd/ItemTextField/ItemTextField.styled.ts
  src/components/GiftAdd/ItemTextField/ItemTextField.tsx
  src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.tsx
  src/components/common/MiniTimer/MiniTimer.styled.ts
  src/components/common/MiniTimer/MiniTimer.tsx
Labels: fix 🛠️, style🎨, 선물등록 🎁

#401 [1.5차 QA] 선물홈 스타일 QA 반영, 선물등록 모달창 추가
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayout.tsx
  src/components/GiftHome/GiftHome2030Gifts/GiftHome2030Gifts.tsx
  src/components/GiftHome/GiftHomeFriendsGifts/GiftHomeFriendsGifts.tsx
  src/components/GiftHome/GiftHomeMyGifts/GiftHomeMyGiftsItem.style.ts
  src/components/GiftHome/common/GiftHomeShowcase.styled.ts
  src/components/GiftHome/common/GiftHomeShowcaseItem.styled.ts
  src/components/common/Modal/DeleteModal.style.ts
  src/components/common/Modal/DeleteModal.tsx
  src/pages/GiftHome/GiftHomeMyGifts/GiftHomeMyGifts.style.ts
  src/pages/GiftHomeDetail/GiftHomeDetail.tsx
Labels: fix 🛠️, style🎨, 선물홈 🎁

#399 [마이페이지] style qa를 위한 변경 사항
  public/svg/mypage_background.svg
  src/assets/svg/MypageBackground.tsx
  src/assets/svg/MypageImage.tsx
  src/assets/svg/index.ts
  src/components/CardRoom/CardRoom.style.ts
  src/components/CardRoom/DoneCardRoom.tsx
  src/components/CardRoom/EditCardRoom.tsx
  src/components/CardRoom/ProgressCardRoom.tsx
  src/components/HomeMypageHeader/HomeMypageHeader.style.ts
  src/components/HomeMypageHeader/HomeMypageHeader.tsx
  src/pages/MyPage/EditRoom/EditRoom.style.ts
  src/pages/MyPage/EditRoom/EditRoom.tsx
  src/pages/MyPage/GiftRoomView/DoneGiftView/DoneGiftView.style.ts
  src/pages/MyPage/GiftRoomView/ProgressGiftView/ProgressGiftView.style.ts
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
Labels: fix 🛠️, refactor ⚙️, style🎨, 마이페이지 👤

#395 [온보딩] 썸네일 미리보기 이미지 짤리는 현상
  src/components/OnBoardingSteps/Step02/Step02.tsx
  src/components/OnBoardingSteps/Step06/Step06.tsx
  src/hooks/common/usePreviewImage.tsx
  src/pages/Participants/ParticipantsView.tsx
Labels: feat💡, 온보딩 📝

#417 Develop -> main
  src/components/Tournament/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.tsx
Labels: merge 🎯

#397 [1.5차 QA] 선물 홈 - 토스트 메시지 추가, 헤더 변경, 카운트다운에 따른 네비게이션
  package.json
  src/App.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithoutLinkLayout.tsx
  src/components/GiftAdd/AddGiftLink/GiftAddFirstLinkLayout/GiftAddFirstLinkLayout.tsx
  src/components/GiftAdd/AddGiftLink/common/LinkAddHeader/LinkAddHeader.tsx
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayout.tsx
  src/components/GiftHome/CountDownTimer/CountDownTimer.tsx
  src/components/GiftHome/GiftHomeHeader/GiftHomeHeader.style.ts
  src/components/GiftHome/GiftHomeHeader/GiftHomeHeader.tsx
  src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.tsx
  src/components/common/MiniTimer/MiniTimer.tsx
  src/context/AddGift/AddGiftContext.tsx
  src/context/GifteeName/GifteeNameContext.tsx
  src/hooks/gift/useHandleCountDownZero.tsx
  src/hooks/useCopyClip.tsx
  src/pages/GiftAdd/GiftAddPage.tsx
  src/pages/GiftHome/GiftHome.tsx
  src/pages/GiftHomeDetail/GiftHomeDetail.tsx
  src/pages/GiftHomeDetail/GiftHomeDetail2030.tsx
  src/pages/GiftHomeDetail/GiftHomeDetailFriends.tsx
  src/router/Router.tsx
  src/style/toast.style.ts
  src/types/product/index.d.ts
  src/types/room/index.d.ts
  yarn.lock
Labels: fix 🛠️, feat💡, 선물홈 🎁

#400 [온보딩] 새롭게 바뀐 step06 (OnboardingFinal) 구현
  public/svg/ic_after_tournament_progress_line.svg
  public/svg/ic_before_tournament_progress_line.svg
  public/svg/ic_nopoint.svg
  public/svg/ic_onboarding_final.svg
  public/svg/ic_point.svg
  src/assets/svg/IcAfterTournamentProgressLine.tsx
  src/assets/svg/IcBeforeTournamentProgressLine.tsx
  src/assets/svg/IcNopoint.tsx
  src/assets/svg/IcOnboardingFinal.tsx
  src/assets/svg/IcPoint.tsx
  src/assets/svg/index.ts
  src/components/OnBoardingSteps/Step05/SelectTimeOptions.tsx
  src/components/OnBoardingSteps/Step06/OnboardingFinalFooter.tsx
  src/components/OnBoardingSteps/Step06/Step06.style.ts
  src/components/OnBoardingSteps/Step06/Step06.tsx
  src/components/common/Button/Radio/BtnRadio.style.ts
  src/components/common/Button/Radio/BtnRadio.tsx
  src/core/routes.ts
  src/hooks/onboarding/useFormatDate.tsx
  src/pages/Participants/ParticipantsView.tsx
Labels: feat💡, style🎨, 온보딩 📝

#412 [온보딩] 스타일 qa 반영 24.02.23 16:14 기준
  src/components/OnBoardingSteps/Step01/Step01.style.ts
  src/components/OnBoardingSteps/Step03/Step03.style.ts
  src/components/OnBoardingSteps/Step03/Step03.tsx
  src/components/OnBoardingSteps/Step04/Step04.style.ts
  src/components/OnBoardingSteps/Step04/Step04.tsx
  src/components/OnBoardingSteps/Step04/TimePicker.tsx
Labels: style🎨, 온보딩 📝

#425 [선물방 메인] 올바른 url로 복사를 위한 env 파일 변경 및 '/'추가
  src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.tsx
Labels: chore🧹

#426 올바른 url로 복사를 위한 env 파일 변경 및 '/'추가
  src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.tsx
Labels: chore🧹

#434 [시작페이지] 2차 qa 내용 반영입니다 !
  src/assets/svg/IcDown.tsx
  src/components/Footer/Footer.tsx
  src/pages/LoginError/LoginError.style.ts
  src/pages/Start/LogoHeader/LogoHeader.style.ts
  src/pages/Start/Start.style.ts
  src/pages/Start/Start.tsx
  src/pages/Start/StartAnimation/DownIconAnimation/StartDownIconAnimation.style.ts
  src/pages/Start/StartAnimation/DownIconAnimation/StartDownIconAnimation.tsx
  src/pages/Start/StartAnimation/GiftAnimation/StartGiftAnimation.style.ts
Labels: refactor ⚙️, style🎨, 시작페이지 📄

#428 [온보딩]입장하기 버튼 클릭 시 아무 작동 없던 문제 해결
  src/components/OnBoardingSteps/Step06/OnboardingFinalFooter.tsx
  src/pages/Participants/ParticipantsView.tsx
Labels: fix 🛠️

#445 공토 컴포넌트 공유를 위한 임시 PR입니다
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayout.tsx
  src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.tsx
  src/components/common/Modal/DeleteModal.tsx
  src/hooks/useCopyClip.tsx
  src/pages/GiftHome/GiftHome.tsx
  src/style/GlobalStyle.ts
Labels: refactor ⚙️

#435 [온보딩] 뒤로가기 시 이미지 미리보기 안보이는 현상 & 유저가 시간먼저 선택 시 발생하는 문제 수정
  src/components/OnBoardingSteps/Step02/Step02.style.ts
  src/components/OnBoardingSteps/Step02/Step02.tsx
  src/components/OnBoardingSteps/Step04/TimePicker.tsx
  src/context/Onboarding/OnboardingContext.tsx
  src/context/Onboarding/PreviewImageContext.tsx
  src/core/toast-messages.ts
  src/hooks/common/usePreviewImage.tsx
  src/hooks/onboarding/useTimerOpen.tsx
  src/hooks/onboarding/useTournamentScheduleCalendar.tsx
  src/router/Router.tsx
  src/types/Onboarding/index.ts
Labels: feat💡, 온보딩 📝

#446 [토너먼트] 2차 QA 스타일 변경사항
  src/components/Tournament/Intro/TournamentIntroContainer.tsx
  src/components/Tournament/TournamentFlow/TournamentCard/TournamentCard.style.ts
  src/components/Tournament/TournamentRanking/TournamentRanking.tsx
  src/components/Tournament/TournamentRanking/TournamentRankingCard/TournamentRankingCard.style.ts
  src/components/Tournament/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.style.ts
Labels: style🎨, 토너먼트 🏆

#450 [선물 등록] 선물 등록 완료 버튼 활성화 기능 수정
  src/components/GiftAdd/AddGiftFooter/AddGiftFooter.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithoutLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx
  src/components/GiftAdd/AddGiftLayout/common/WriteItemInfo/WithoutLinkWriteItemInfo.tsx
  src/components/GiftAdd/AddGiftLayout/common/WriteItemInfo/WriteItemInfo.tsx
  src/components/GiftAdd/AddGiftLink/GiftAddFirstLinkLayout/GiftAddFirstLinkLayout.tsx
  src/components/GiftAdd/AddGiftLink/common/LinkAddHeader/LinkAddHeader.tsx
  src/context/AddGift/AddGiftContext.tsx
  src/hooks/queries/gift/usePostGift.tsx
  src/hooks/useConvertURLtoFile.tsx
  src/pages/GiftAdd/GiftAddPage.tsx
Labels: fix 🛠️, refactor ⚙️, 선물등록 🎁

#451 [온보딩] 사파리에서 날짜 형식 NaN, undefined 뜨는 현상 수정
  src/components/OnBoardingSteps/Step06/Step06.tsx
  src/core/toast-messages.ts
  src/pages/Participants/ParticipantsView.tsx
Labels: fix 🛠️

#454 이미지 최소, 최대 길이 5000px로 수정
  src/components/Tournament/TournamentFlow/TournamentFlowContainer.tsx
  src/components/Tournament/TournamentFlow/TournamentFlowLogic.tsx
  src/core/toast-messages.ts
Labels: fix 🛠️, merge 🎯

#457 [선물 등록] 링크 입력 이름 추가
  src/components/GiftAdd/AddGiftLink/GiftAddFirstLinkLayout/GiftAddFirstLinkLayout.tsx
  src/components/GiftHome/common/GiftHomeShowcaseItem.styled.ts
Labels: fix 🛠️, 선물등록 🎁
