Repository SWEET-DEVELOPERS/sweet-client, pull requests merged in 2024-01, with the labels that each got.

#4 [초기세팅] GitHub Actions 설정
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
Labels: 초기세팅

#14 [초기세팅] eslint 설정 및 prettier 설정
  .eslintrc.cjs
  .prettierrc
  package.json
  yarn.lock
Labels: 초기세팅

#7 [초기세팅] GlobalStyle 작성
  index.html
  package.json
  src/App.tsx
  src/style/GlobalStyle.ts
  utils/setScreenSize.ts
  yarn.lock
Labels: 초기세팅

#8 [초기세팅] Formatting 파일 구조 및 라우팅 설정
  package.json
  src/App.tsx
  src/apis/.keep
  src/components/.keep
  src/components/common/DashBoard.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Router.tsx
  src/core/.keep
  src/hooks/.keep
  src/pages/Main.tsx
  src/pages/Mypage.tsx
  src/shared/.keep
  src/shared/recoils/.keep
  src/styles/.keep
  src/types/.keep
  src/utils/.keep
  yarn.lock
Labels: 초기세팅

#15 [초기세팅] husky 설정 및 lint staged 설정
  .commitlintrc.json
  package.json
  yarn.lock
Labels: 초기세팅

#17 [초기세팅] recoil 설치 및 파일 설정
  package.json
  src/App.tsx
  src/recoil/atoms.ts
  yarn.lock
Labels: 초기세팅

#18 [초기세팅] react-query 설치 및 세팅 및 key 파일 생성
  package.json
  src/App.tsx
  src/apis/queryKeys.ts
  yarn.lock
Labels: 초기세팅

#16 [초기세팅] svgr 설치 / open-graph
  package.json
  public/svg/vite.svg
  src/assets/custom.d.ts
  src/assets/svg/Vite.tsx
  src/assets/svg/index.ts
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 초기세팅

#25 [초기세팅] Github Actions 수정(Vercel 배포 연결, preview 수정)
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
  build.sh
Labels: 초기세팅

#23 [초기세팅] 자주 사용하는 속성들 mixin 설정
  src/main.tsx
  src/style/index.tsx
  src/style/mixin.ts
  src/style/theme.ts
Labels: 초기세팅

#24 [리드미] 웹 레포 리드미 작성
  README.md
Labels: docs

#37 초기세팅/theme 설정
  src/assets/fonts/SUIT-Regular.ttf
  src/assets/fonts/SUIT-SemiBold.ttf
  src/assets/fonts/fonts.d.ts
  src/assets/fonts/index.ts
  src/style/theme.ts
Labels: 초기세팅

#28 [초기세팅] 화면 사이즈 layout 분리
  src/App.tsx
  src/components/common/DashBoard.tsx
  src/components/common/Router.tsx
  src/hooks/useMobile.tsx
  src/layouts/Layout.tsx
  src/router/Router.tsx
Labels: style

#43 [초기세팅] theme fonts, colors 구조 수정
  src/style/theme.ts
Labels: 초기세팅

#45 [초기세팅] 모바일 리사이징 레이아웃 적용 안되는 이슈 해결
  src/hooks/useMobile.tsx
  src/layouts/Layout.tsx
  src/style/GlobalStyle.ts
  utils/setScreenSize.ts
Labels: fix, 초기세팅, style

#39 [초기세팅] PR 미리보기 액션 수정
  .github/workflows/preview.yml
  src/assets/svg/Vite.tsx
Labels: 초기세팅

#50 [온보딩페이지] STEP01 이름 입력 컴포넌트 뷰 구현 & 나머지 단계 타이틀만 구현
  src/App.css
  src/App.tsx
  src/components/common/title/SubTitle.tsx
  src/components/common/title/Title.style.ts
  src/components/common/title/Title.tsx
  src/components/onboarding/step01/Step01.style.ts
  src/components/onboarding/step01/Step01.tsx
  src/components/onboarding/step02/Step02.tsx
  src/components/onboarding/step03/Step03.tsx
  src/components/onboarding/step04/Step04.tsx
  src/components/onboarding/step05/Step05.tsx
  src/core/onboarding.ts
  src/index.css
  src/main.tsx
  src/pages/OnBoardingPage.tsx
  src/router/Router.tsx
Labels: feat, style

#51 [선물홈 세부 페이지] 친구 등록, 2030 세부 페이지 UI 구현
  src/components/common/MiniTimer/MiniTimer.styled.ts
  src/components/common/MiniTimer/MiniTimer.tsx
  src/pages/GiftAddPage/GiftAddPage.tsx
  src/pages/GiftHomeDetail/GiftHomeDetail.styled.ts
  src/pages/GiftHomeDetail/GiftHomeDetail2030.tsx
  src/pages/GiftHomeDetail/GiftHomeDetailFriends.tsx
  src/router/Router.tsx
  src/style/GlobalStyle.ts
Labels: 기능구현, feat, 공통 컴포넌트, 세부페이지

#57 [공통컴포넌트] Button 10가지 구현
  public/svg/ic_circle.svg
  public/svg/ic_circle_pink.svg
  public/svg/ic_kakao_small.svg
  public/svg/ic_kako_large.svg
  src/assets/svg/IcCircle.tsx
  src/assets/svg/IcCirclePink.tsx
  src/assets/svg/IcEdit2.tsx
  src/assets/svg/IcKakaoSmall.tsx
  src/assets/svg/IcKakoLarge.tsx
  src/assets/svg/IcRight.tsx
  src/assets/svg/index.ts
  src/components/common/Button/Change/BtnChange.style.ts
  src/components/common/Button/Change/BtnChange.tsx
  src/components/common/Button/Cta/SmallStroke/BtnSmallStroke.style.ts
  src/components/common/Button/Cta/SmallStroke/BtnSmallStroke.tsx
  src/components/common/Button/Cta/fill/BtnFill.style.ts
  src/components/common/Button/Cta/fill/BtnFill.tsx
  src/components/common/Button/Cta/medium/BtnMedium.style.ts
  src/components/common/Button/Cta/medium/BtnMedium.tsx
  src/components/common/Button/Edit/BtnEdit.style.ts
  src/components/common/Button/Edit/BtnEdti.tsx
  src/components/common/Button/Logout/BtnLogout.style.ts
  src/components/common/Button/Logout/BtnLogout.tsx
  src/components/common/Button/Next/BtnNext.style.ts
  src/components/common/Button/Next/BtnNext.tsx
  src/components/common/Button/Radio/BtnRadio.style.ts
  src/components/common/Button/Radio/BtnRadio.tsx
  src/components/common/Button/Registration/BtnRegistration.style.ts
  src/components/common/Button/Registration/BtnRegistration.tsx
  src/components/common/Button/Subtitle/BtnSubtitle.style.ts
  src/components/common/Button/Subtitle/BtnSubtitle.tsx
  src/pages/GiftAddPage/GiftAddPage.tsx
  src/style/theme.ts
  src/styles/.keep
Labels: feat, 공통 컴포넌트

#61 [공통컴포넌트 ] button customstyle 추가
  src/components/common/Button/Change/BtnChange.tsx
  src/components/common/Button/Cta/SmallStroke/BtnSmallStroke.tsx
  src/components/common/Button/Cta/fill/BtnFill.tsx
  src/components/common/Button/Cta/medium/BtnMedium.tsx
  src/components/common/Button/Edit/BtnEdti.tsx
  src/components/common/Button/Logout/BtnLogout.tsx
  src/components/common/Button/Next/BtnNext.tsx
  src/components/common/Button/Radio/BtnRadio.tsx
  src/components/common/Button/Registration/BtnRegistration.tsx
  src/components/common/Button/Subtitle/BtnSubtitle.tsx
Labels: refactor, 공통 컴포넌트

#54 [토너먼트] 토너먼트 인트로 화면 퍼블리싱
  public/svg/3dicons.svg
  src/assets/svg/3Dicons.tsx
  src/assets/svg/index.ts
  src/components/.keep
  src/components/tournament/intro/TournamentContainer.tsx
  src/components/tournament/intro/tournamentItemCount/TournamentItemCount.style.ts
  src/components/tournament/intro/tournamentItemCount/TournamentItemCount.tsx
  src/components/tournament/intro/tournamentStartButton/TournamentStartButton.tsx
  src/components/tournament/intro/tournamentStartText/TournamentStartText.style.ts
  src/components/tournament/intro/tournamentStartText/TournamentStartText.tsx
  src/pages/TournamentPage.tsx
  src/recoil/atoms.ts
  src/router/Router.tsx
Labels: feat, style, 토너먼트

#59 [토너먼트] 토너먼트 라운딩 카드 제작 완료
  public/svg/logo.svg
  src/assets/img/Rectangle.png
  src/assets/svg/Logo.tsx
  src/assets/svg/index.ts
  src/components/TournamentFlowContainer.tsx
  src/components/tournament/tournamentFlow/tournamentCard/TournamentCard.style.ts
  src/components/tournament/tournamentFlow/tournamentCard/TournamentCard.tsx
  src/components/tournament/tournamentFlow/tournamentFooter/TournamentFooter.tsx
  src/components/tournament/tournamentFlow/tournamentTitle/TournamentTitle.tsx
  src/pages/TournamentOngoing.tsx
  src/router/Router.tsx
Labels: style, 토너먼트

#80 [공통컴포넌트] 모달창 구현
  src/components/common/Button/Cta/medium/BtnMedium.style.ts
  src/components/common/Modal/Modal.style.ts
  src/components/common/Modal/Modal.tsx
Labels: feat, 공통 컴포넌트

#72 [토너먼트] 토너먼트 플로우 화면 퍼블리싱
  public/svg/ic_external_gray.svg
  public/svg/ic_refresh_gray.svg
  src/assets/svg/IcExternalGray.tsx
  src/assets/svg/IcRefreshGray.tsx
  src/assets/svg/index.ts
  src/components/common/Button/Next/BtnNext.style.ts
  src/components/common/Header.tsx
  src/components/tournament/intro/TournamentContainer.tsx
  src/components/tournament/tournamentFlow/TournamentFlowContainer.style.ts
  src/components/tournament/tournamentFlow/TournamentFlowContainer.tsx
  src/components/tournament/tournamentFlow/tournamentCard/TournamentCard.style.ts
  src/components/tournament/tournamentFlow/tournamentCard/TournamentCard.tsx
  src/components/tournament/tournamentFlow/tournamentFooter/TournamentFooter.style.ts
  src/components/tournament/tournamentFlow/tournamentFooter/TournamentFooter.tsx
  src/components/tournament/tournamentFlow/tournamentTitle/TournamentTitle.tsx
  src/components/tournament/tournamentFlow/tournamentTitle/TournamernTitle.style.ts
  src/pages/TournamentOngoing.tsx
  src/style/theme.ts
Labels: feat, style, 토너먼트

#82 [토너먼트] 토너먼트 결과 화면 퍼블리싱
  src/components/common/Button/Cta/fill/BtnFill.style.ts
  src/components/tournament/TournamentFlowContainer.tsx
  src/components/tournament/TournamentResult/TournamentResult.tsx
  src/components/tournament/TournamentResult/TournamentResultCard/TournamentResultCard.style.ts
  src/components/tournament/TournamentResult/TournamentResultCard/TournamentResultCard.tsx
  src/components/tournament/TournamentResult/TournamentResultFooter/TournamentResultFooter.tsx
  src/components/tournament/TournamentResult/TournamentResultUser/TournamentResultUser.tsx
  src/components/tournament/TournamentResult/TournamentTitle/TournamentTitle.tsx
  src/components/tournament/intro/TournamentContainer.tsx
  src/components/tournament/tournamentFlow/TournamentFlowContainer.tsx
  src/components/tournament/tournamentFlow/tournamentCard/TournamentCard.tsx
  src/pages/TournamentOngoing.tsx
Labels: feat, style, 토너먼트

#86 [토너먼트] 최종 순위 확인 뷰 퍼블리싱
  public/svg/ic_img_share.svg
  public/svg/ic_link_share.svg
  public/svg/ic_medal_1.svg
  public/svg/ic_medal_2.svg
  public/svg/ic_medal_3.svg
  public/svg/image 477.svg
  src/assets/svg/IcImgShare.tsx
  src/assets/svg/IcLinkShare.tsx
  src/assets/svg/IcMedal1.tsx
  src/assets/svg/IcMedal2.tsx
  src/assets/svg/IcMedal3.tsx
  src/assets/svg/Image477.tsx
  src/assets/svg/index.ts
  src/components/common/title/Price/PriceTag.style.ts
  src/components/common/title/Price/PriceTag.tsx
  src/components/tournament/TournamentRanking/TournamentRanking.style.ts
  src/components/tournament/TournamentRanking/TournamentRanking.tsx
  src/components/tournament/TournamentRanking/TournamentRankingCard/TournamentRankingCard.style.ts
  src/components/tournament/TournamentRanking/TournamentRankingCard/TournamentRankingCard.tsx
  src/components/tournament/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.style.ts
  src/components/tournament/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.tsx
  src/components/tournament/TournamentResult/TournamentResultCard/TournamentResultCard.tsx
  src/components/tournament/intro/TournamentContainer.tsx
  src/components/tournament/tournamentFlow/tournamentCard/TournamentCard.tsx
Labels: style, 토너먼트

#65 [선물 등록 페이지] 내가 등록한 선물 페이지 UI 구현
  public/svg/ic_empty_box.svg
  src/assets/svg/IcCancel.tsx
  src/assets/svg/IcEmptyBox.tsx
  src/assets/svg/index.ts
  src/components/GiftAdd/GiftAddButtons/GiftAddButtonsWrapper.styled.ts
  src/components/GiftAdd/GiftAddButtons/GiftAddButtonsWrapper.tsx
  src/components/GiftAdd/GiftAddCompleteBtn/GiftAddCompleteBtn.styled.ts
  src/components/GiftAdd/GiftAddCompleteBtn/GiftAddCompleteBtn.tsx
  src/components/GiftAdd/GiftAddPageBottomSection/GiftAddPageBottom.styled.ts
  src/components/GiftAdd/GiftAddPageBottomSection/GiftAddPageBottom.tsx
  src/components/common/MiniTimer/MiniTimer.styled.ts
  src/components/common/Router.tsx
  src/pages/AddGift.tsx
  src/pages/GiftAddPage/GiftAddPage.styled.ts
  src/pages/GiftAddPage/GiftAddPage.tsx
  src/pages/GiftLinkPage/GiftLinkPage.styled.ts
  src/pages/GiftLinkPage/GiftLinkPage.tsx
  src/router/Router.tsx
Labels: 기능구현, feat, 선물등록

#97 [최신화] 기존 브랜치에서 새로운 브랜치로 코드 복붙
  package.json
  public/svg/ic_empty_thumbnail.svg
  public/svg/ic_kakao_share.svg
  src/assets/svg/IcEmptyThumbnail.tsx
  src/assets/svg/IcKakaoShare.tsx
  src/assets/svg/index.ts
  src/components/OnBoardingSteps/Step01/Step01.tsx
  src/components/OnBoardingSteps/Step02/Step02.style.ts
  src/components/OnBoardingSteps/Step02/Step02.tsx
  src/components/OnBoardingSteps/Step03/Step03.style.ts
  src/components/OnBoardingSteps/Step03/Step03.tsx
  src/components/OnBoardingSteps/Step04/Step04.style.ts
  src/components/OnBoardingSteps/Step04/Step04.tsx
  src/components/OnBoardingSteps/Step05/Step05.style.ts
  src/components/OnBoardingSteps/Step05/Step05.tsx
  src/components/OnBoardingSteps/Step06/Step06.style.ts
  src/components/OnBoardingSteps/Step06/Step06.tsx
  src/components/OnBoardingSteps/Step06/image_sample.png
  src/components/OnBoardingSteps/onboardingBtn/OnBoardingBtn.style.ts
  src/components/OnBoardingSteps/onboardingBtn/OnBoardingBtn.tsx
  src/components/OnBoardingSteps/onboardingHeader/OnBoardingHeader.tsx
  src/components/OnBoardingSteps/onboardingNextBtnWrapper/OnBoardingNextBtnWrapper.style.ts
  src/components/OnBoardingSteps/onboardingNextBtnWrapper/OnBoardingNextBtnWrapper.tsx
  src/components/common/Button/Radio/BtnRadio.style.ts
  src/components/common/Button/Radio/BtnRadio.tsx
  src/pages/OnBoardingPage.tsx
  yarn.lock
Labels: fix

#91 [선물홈] 선물홈 UI 구현
  package.json
  public/svg/ic_time_colon.svg
  public/svg/ic_time_count.svg
  src/assets/svg/IcTimeColon.tsx
  src/assets/svg/IcTimeCount.tsx
  src/assets/svg/index.ts
  src/components/GiftHome/CountDownTimer/ CountDownCard/CountDownCard.styled.ts
  src/components/GiftHome/CountDownTimer/ CountDownCard/CountDownCard.tsx
  src/components/GiftHome/CountDownTimer/CountDownTimer.styled.ts
  src/components/GiftHome/CountDownTimer/CountDownTimer.tsx
  src/components/GiftHome/GiftHome2030Gifts/GiftHome2030Gifts.tsx
  src/components/GiftHome/GiftHome2030Gifts/GiftHome2030Item.tsx
  src/components/GiftHome/GiftHomeFriendsGifts/GiftHomeFriendsGifts.tsx
  src/components/GiftHome/GiftHomeFriendsGifts/GiftHomeFriendsItem.tsx
  src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.styled.ts
  src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.tsx
  src/components/GiftHome/common/GiftHomeShowcase.styled.ts
  src/components/GiftHome/common/GiftHomeShowcaseItem.styled.ts
  src/layouts/Layout.tsx
  src/pages/GiftHome/GiftHome.styled.ts
  src/pages/GiftHome/GiftHome.tsx
  src/router/Router.tsx
  src/style/theme.ts
  yarn.lock
Labels: 기능구현, feat, 선물홈

#100 [선물 홈, 선물 등록] 전반적인 뷰 수정 및 플로우 연결
  public/svg/Ic_bookmark.svg
  src/App.css
  src/assets/svg/IcBookmark.tsx
  src/assets/svg/index.ts
  src/components/GiftAdd/AddGiftLayout/AddGiftWithLinkLayout.tsx
  src/components/GiftAdd/GiftAddButtons/GiftAddButtonsWrapper.styled.ts
  src/components/GiftAdd/GiftAddButtons/GiftAddButtonsWrapper.tsx
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayout.tsx
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayoutHeader.style.ts
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayoutHeader.tsx
  src/components/GiftHome/GiftHome2030Gifts/GiftHome2030Gifts.tsx
  src/components/GiftHome/GiftHomeFriendsGifts/GiftHomeFriendsGifts.tsx
  src/components/GiftHome/GiftHomeHeader/GiftHomeHeader.style.ts
  src/components/GiftHome/GiftHomeHeader/GiftHomeHeader.tsx
  src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.styled.ts
  src/components/GiftHome/common/GiftHomeShowcase.styled.ts
  src/components/GiftHome/common/GiftHomeShowcaseHeader/GiftHoeShowcaseHeader.style.ts
  src/components/GiftHome/common/GiftHomeShowcaseHeader/GiftHomeShowcaseHeader.tsx
  src/components/common/Router.tsx
  src/index.css
  src/pages/AddGift.tsx
  src/pages/GiftAdd/GiftAddPage.tsx
  src/pages/GiftHome/GiftHome.styled.ts
  src/pages/GiftHome/GiftHome.tsx
  src/router/Router.tsx
Labels: 기능구현, feat, 선물등록, 선물홈

#107 [마이페이지] react-query 데이터 패칭 방식 예시 코드 작성
  src/App.css
  src/App.tsx
  src/apis/.keep
  src/apis/client.ts
  src/apis/queryKeys.ts
  src/components/CardRoom/CardRoom.style.ts
  src/components/CardRoom/DoneCardRoom.tsx
  src/components/CardRoom/EditCardRoom.tsx
  src/components/CardRoom/ProgressCardRoom.tsx
  src/components/Login/index.tsx
  src/hooks/queries/member/index.ts
  src/hooks/queries/member/useGetMypage.tsx
  src/hooks/queries/member/useLogin.tsx
  src/index.css
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.style.ts
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.tsx
  src/pages/MyPage/Detail/DetailHeader/DetailHeader.style.ts
  src/pages/MyPage/Detail/DetailHeader/DetailHeader.tsx
  src/pages/MyPage/Detail/DetailProgressRoom/DetailProgress.style.ts
  src/pages/MyPage/Detail/DetailProgressRoom/DetailProgressRoom.tsx
  src/pages/MyPage/Detail/EmptyView/EmptyView.style.ts
  src/pages/MyPage/Detail/EmptyView/EmptyView.tsx
  src/pages/MyPage/EditRoom/CardGuest/CardGuest.style.ts
  src/pages/MyPage/EditRoom/CardGuest/CardGuest.tsx
  src/pages/MyPage/EditRoom/EditRoom.style.ts
  src/pages/MyPage/EditRoom/EditRoom.tsx
  src/pages/MyPage/GiftRoomView/DoneGiftView/DoneGiftView.style.ts
  src/pages/MyPage/GiftRoomView/DoneGiftView/DoneGiftView.tsx
  src/pages/MyPage/GiftRoomView/GiftRoomHeader/GiftRoomHeader.style.ts
  src/pages/MyPage/GiftRoomView/GiftRoomHeader/GiftRoomHeader.tsx
  src/pages/MyPage/GiftRoomView/ProgressGiftView/ProgressGiftView.style.ts
  src/pages/MyPage/GiftRoomView/ProgressGiftView/ProgressGiftView.tsx
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/ProfileImage/ProfileImage.style.ts
  src/pages/MyPage/ProfileImage/ProfileImage.tsx
  src/pages/Start/Start.tsx
  src/router/Router.tsx
  src/types/user/index.d.ts
Labels: feat, 마이페이지

#111 [토너먼트] 라운딩 로직 및 부전승 처리
  src/assets/img/Rectangle082.png
  src/assets/img/img.png
  src/assets/img/tournament_bg_03.png
  src/assets/img/tournament_bg_final.png
  src/assets/img/tournament_finish_final.png
  src/components/TournamentNew/Intro/TournamentContainer.tsx
  src/components/TournamentNew/Intro/TournamentItemCount/TournamentItemCount.tsx
  src/components/TournamentNew/Intro/TournamentStartButton/TournamentStartButton.tsx
  src/components/TournamentNew/TournamentFlow/TournamentCard/TournamentCard.tsx
  src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.style.ts
  src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.tsx
  src/components/TournamentNew/TournamentFlow/TournamentFooter/TournamentFooter.tsx
  src/components/TournamentNew/TournamentFlow/TournamentTitle/TournamentTitle.tsx
  src/components/TournamentNew/TournamentFlow/TournamentTitle/TournamernTitle.style.ts
  src/components/TournamentNew/TournamentResult/TournamentResult.sytle.ts
  src/components/TournamentNew/TournamentResult/TournamentResult.tsx
  src/components/TournamentNew/TournamentResult/TournamentResultCard/TournamentResultCard.tsx
  src/core/mockupData.ts
  src/hooks/tournament/useTournament.tsx
  src/pages/TournamentOngoing.tsx
  src/router/Router.tsx
Labels: 기능구현, feat, 토너먼트

#114 [선물홈, 선물등록, 세부페이지] api 타입 및 hooks 파일 생성
  src/hooks/queries/etc/index.ts
  src/hooks/queries/etc/usePostOpengraph.tsx
  src/hooks/queries/gift/index.ts
  src/hooks/queries/gift/useDeleteMyGift.tsx
  src/hooks/queries/gift/useGetFriendGift.tsx
  src/hooks/queries/gift/useGetMyGift.tsx
  src/hooks/queries/gift/usePostGift.tsx
  src/hooks/queries/product/index.ts
  src/hooks/queries/product/useGetHotProduct.tsx
  src/hooks/queries/room/index.ts
  src/hooks/queries/room/useGetRoomInfo.tsx
  src/types/etc/index.d.ts
  src/types/gift/index.d.ts
  src/types/product/index.d.ts
  src/types/room/index.d.ts
Labels: 기능구현, feat, 선물등록, 세부페이지, 선물홈, API

#110 [온보딩] 온보딩 POST & 카카오 공유하기
  index.html
  src/apis/client.ts
  src/components/OnBoardingSteps/Step01/Step01.style.ts
  src/components/OnBoardingSteps/Step01/Step01.tsx
  src/components/OnBoardingSteps/Step02/Step02.tsx
  src/components/OnBoardingSteps/Step03/Step03.style.ts
  src/components/OnBoardingSteps/Step03/Step03.tsx
  src/components/OnBoardingSteps/Step04/Step04.style.ts
  src/components/OnBoardingSteps/Step04/Step04.tsx
  src/components/OnBoardingSteps/Step05/Step05.style.ts
  src/components/OnBoardingSteps/Step05/Step05.tsx
  src/components/OnBoardingSteps/Step05/TimeBox.tsx
  src/components/OnBoardingSteps/Step06/Step06.tsx
  src/components/OnBoardingSteps/onboardingBtn/OnBoardingBtn.style.ts
  src/components/OnBoardingSteps/onboardingBtn/OnBoardingBtn.tsx
  src/components/common/Button/Radio/BtnRadio.tsx
  src/hooks/queries/onboarding/usePostOnboardingInfo.tsx
  src/pages/OnBoardingPage.tsx
  src/types/KakaoShare/d.ts
  src/types/Onboarding/index.d.ts
Labels: feat, 온보딩

#117 [토너먼트] 토너먼트 선물 리스트 조회 API
  src/components/TournamentNew/Intro/TournamentContainer.tsx
  src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.tsx
  src/components/TournamentNew/TournamentResult/TournamentResult.tsx
  src/components/TournamentNew/TournamentResult/TournamentResultFooter/TournamentResultFooter.tsx
  src/hooks/queries/tournament/useGetItem.tsx
  src/hooks/queries/tournament/usePostScore.tsx
  src/hooks/tournament/useTournament.tsx
  src/pages/TournamentOngoing.tsx
  src/types/tournament/index.d.ts
Labels: feat, 토너먼트, API

#125 [마이페이지] api 연결 후 기능 구현
  src/apis/queryClients.ts
  src/components/CardRoom/DoneCardRoom.tsx
  src/components/CardRoom/EditCardRoom.tsx
  src/components/CardRoom/ProgressCardRoom.tsx
  src/components/Login/index.tsx
  src/hooks/queries/member/index.ts
  src/hooks/queries/member/useGetActiveRoom.tsx
  src/hooks/queries/member/useGetClosedRoom.tsx
  src/hooks/queries/member/useGetMypage.tsx
  src/hooks/queries/member/useLogin.tsx
  src/hooks/queries/room/useDeleteRoomMember.tsx
  src/hooks/queries/room/useGetRoomMember.tsx
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.style.ts
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.tsx
  src/pages/MyPage/Detail/DetailProgressRoom/DetailProgress.style.ts
  src/pages/MyPage/Detail/DetailProgressRoom/DetailProgressRoom.tsx
  src/pages/MyPage/EditRoom/CardGuest/CardGuest.tsx
  src/pages/MyPage/EditRoom/EditRoom.tsx
  src/pages/MyPage/GiftRoomView/DoneGiftView/DoneGiftView.tsx
  src/pages/MyPage/GiftRoomView/GiftRoomHeader/GiftRoomHeader.tsx
  src/pages/MyPage/GiftRoomView/ProgressGiftView/ProgressGiftView.tsx
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/ProfileImage/ProfileImage.tsx
  src/pages/Start/Start.tsx
  src/router/Router.tsx
  src/types/member/index.d.ts
Labels: feat

#126 Refactor/#88 tournament layout
  src/assets/img/3dic_podium2.png
  src/assets/img/3dic_trophy3.png
  src/components/TournamentNew/Intro/TournamentContainer.tsx
  src/components/TournamentNew/Intro/TournamentContatiner.style.tsx
  src/components/TournamentNew/Intro/TournamentStartButton/TournamentStartButton.style.ts
  src/components/TournamentNew/TournamentFlow/TournamentTitle/TournamernTitle.style.ts
Labels: refactor, style, 토너먼트

#128 [토너먼트] 유저, 시간 그리고 부전승 로직 수정
  src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.tsx
  src/components/TournamentNew/TournamentResult/TournamentResult.tsx
  src/components/TournamentNew/TournamentResult/TournamentResultCard/TournamentResultCard.style.ts
  src/components/TournamentNew/TournamentResult/TournamentResultUser/TournamentResultUser.tsx
  src/components/TournamentNew/TournamentResult/TournamentTitleSub/TournamnetTitleSub.tsx
  src/hooks/queries/tournament/useGetTournamentUser.tsx
  src/types/tournament/index.d.ts
Labels: 기능구현, feat, 토너먼트, API

#130 [토너먼트] 토너먼트 최종 결과 조회 API
  src/components/TournamentNew/Intro/TournamentStartText/TournamentStartText.style.ts
  src/components/TournamentNew/TournamentRanking/TournamentRanking.tsx
  src/components/TournamentNew/TournamentRanking/TournamentRankingCard/TournamentRankingCard.tsx
  src/components/TournamentNew/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.style.ts
  src/components/TournamentNew/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.tsx
  src/hooks/queries/tournament/useGetRanking.tsx
  src/types/tournament/index.d.ts
Labels: feat, 토너먼트, API

#131 [선물홈, 선물등록] 선물 링크 유효성 검사 api 연결, 타이머 기능 구현 마무리
  src/components/GiftAdd/AddGiftLayout/AddGiftWithLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithoutLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.styled.ts
  src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx
  src/components/GiftAdd/AddGiftLink/GiftAddFirstLinkLayout/GiftAddFirstLinkLayout.tsx
  src/components/GiftAdd/AddGiftLink/GiftAddSecondLinkLayout/GiftAddSecondLinkLayout.tsx
  src/components/GiftAdd/AddGiftLink/common/LinkAddHeader/LinkAddHeader.tsx
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayout.tsx
  src/components/GiftAdd/ItemTextField/ItemTextField.styled.ts
  src/components/GiftAdd/ItemTextField/ItemTextField.tsx
  src/components/GiftHome/CountDownTimer/CountDownTimer.tsx
  src/components/GiftHome/GiftHomeSummary/GiftHomeSummary.tsx
  src/components/common/MiniTimer/MiniTimer.tsx
  src/hooks/queries/etc/usePostOpengraph.tsx
  src/hooks/queries/gift/useDeleteMyGift.tsx
  src/hooks/queries/gift/useGetFriendGift.tsx
  src/hooks/queries/gift/usePostGift.tsx
  src/hooks/useCountDown.tsx
  src/pages/GiftAdd/GiftAddPage.tsx
  src/pages/GiftHome/GiftHome.tsx
  src/pages/GiftHomeDetail/GiftHomeDetail2030.tsx
  src/pages/GiftHomeDetail/GiftHomeDetailFriends.tsx
  src/router/Router.tsx
  src/types/etc/index.d.ts
Labels: 기능구현, feat, 선물등록, 세부페이지, 선물홈, API

#140 [토너먼트] 랭킹 화면 API 데이터 패칭
  package.json
  public/svg/ic_medal_4.svg
  src/assets/svg/IcMedal4.tsx
  src/assets/svg/index.ts
  src/components/TournamentNew/TournamentRanking/TournamentRanking.tsx
  src/components/TournamentNew/TournamentRanking/TournamentRankingCard/TournamentRankingCard.tsx
  src/components/TournamentNew/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.tsx
  src/pages/TournamentPage.tsx
  src/router/Router.tsx
  yarn.lock
Labels: feat, 토너먼트, API

#138 [토너먼트] 다음 버튼 로직 구현 및 이미지 불러오기
  src/components/TournamentNew/TournamentFlow/TournamentCard/TournamentCard.tsx
  src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.tsx
  src/components/TournamentNew/TournamentFlow/TournamentFooter/TournamentFooter.style.ts
  src/components/TournamentNew/TournamentFlow/TournamentFooter/TournamentFooter.tsx
  src/components/TournamentNew/TournamentResult/TournamentResultCard/TournamentResultCard.tsx
Labels: 기능구현, feat, 토너먼트

#141 [시작페이지,마이페이지] header, footer
  public/svg/divider.svg
  public/svg/ic_instagram.svg
  public/svg/ic_palmspring.svg
  public/svg/long_divider.svg
  public/svg/sweet_logo_gray.svg
  public/svg/sweet_logo_pink.svg
  src/assets/svg/Divider.tsx
  src/assets/svg/IcInstagram.tsx
  src/assets/svg/IcPalmspring.tsx
  src/assets/svg/LongDivider.tsx
  src/assets/svg/SweetLogoGray.tsx
  src/assets/svg/SweetLogoPink.tsx
  src/assets/svg/index.ts
  src/components/Footer/Footer.style.ts
  src/components/Footer/Footer.tsx
  src/components/SideBar/SideBar.style.ts
  src/components/SideBar/SideBar.tsx
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.style.ts
  src/pages/MyPage/Detail/DetailDoneRoom/DetailDoneRoom.tsx
  src/pages/MyPage/Detail/DetailHeader/DetailHeader.tsx
  src/pages/MyPage/Detail/DetailProgressRoom/DetailProgress.style.ts
  src/pages/MyPage/Detail/DetailProgressRoom/DetailProgressRoom.tsx
  src/pages/MyPage/Detail/EmptyView/EmptyView.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/MyPageHeader/MyPageHeader.style.ts
  src/pages/MyPage/MyPageHeader/MyPageHeader.tsx
  src/pages/Start/Start.tsx
  src/pages/Start/StartHeader/StartHeader.style.ts
  src/pages/Start/StartHeader/StartHeader.tsx
  src/utils/Footer.utils.ts
Labels: feat, 공통 컴포넌트, 마이페이지, 시작페이지, merge

#142 [커스텀훅] 링크복사 함수 커스텀 훅 분리
  src/components/TournamentNew/TournamentRanking/TournamentRanking.style.ts
  src/components/TournamentNew/TournamentRanking/TournamentRanking.tsx
  src/components/TournamentNew/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.tsx
  src/hooks/useCopyClip.tsx
Labels: feat, refactor, 공통 컴포넌트

#157 [선물 등록, 선물 홈] presignedUrl, 가격 포맷팅, 링크 가져오기, 미니타이머
  src/components/GiftAdd/AddGiftFooter/AddGiftFooter.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/AddGiftWithoutLinkLayout.tsx
  src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.styled.ts
  src/components/GiftAdd/AddGiftLayout/common/AddGiftImg/AddGiftImg.tsx
  src/components/GiftAdd/AddGiftLayout/common/WriteItemInfo/WriteItemInfo.tsx
  src/components/GiftAdd/AddGiftLink/GiftAddFirstLinkLayout/GiftAddFirstLinkLayout.tsx
  src/components/GiftAdd/GiftAddButtons/GiftAddButtonsWrapper.tsx
  src/components/GiftAdd/GiftAddPageLayout/GiftAddPageLayout.tsx
  src/hooks/queries/etc/usePostMyPresignedUrl.tsx
  src/hooks/queries/gift/usePostGift.tsx
  src/pages/GiftAdd/GiftAddPage.tsx
  src/router/Router.tsx
Labels: 기능구현, feat, 선물홈, merge, API

#163 [공통] 폰트 적용 및 토너먼트 타이머 시도
  index.html
  src/components/TournamentNew/Intro/TournamentContainer.tsx
  src/components/TournamentNew/Intro/TournamentStartText/TournamentStartText.style.ts
  src/components/TournamentNew/Intro/TournamentStartText/TournamentStartText.tsx
  src/components/TournamentNew/TournamentRanking/TournamentRanking.tsx
  src/components/TournamentNew/TournamentRanking/TournamentRankingTitle/TournamentRankingTitle.tsx
  src/pages/TournamentPage.tsx
  src/router/Router.tsx
Labels: fix, style

#173 [토너먼트] outlink 보러가기 기능 구현 및 스타일 수정
  src/components/TournamentNew/TournamentFlow/TournamentCard/TournamentCard.style.ts
  src/components/TournamentNew/TournamentFlow/TournamentCard/TournamentCard.tsx
  src/core/mockupData.ts
Labels: feat, style, 토너먼트

#178 [토너먼트] 리프레쉬 아이콘 작동 및 스타일 수정
  src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.tsx
  src/components/TournamentNew/TournamentFlow/TournamentTitle/TournamentTitle.tsx
  src/components/TournamentNew/TournamentFlow/TournamentTitle/TournamernTitle.style.ts
  src/types/tournament/index.d.ts
Labels: feat, 토너먼트

#182 [토너먼트] 다음버튼 활성화, 타이머 세팅, 다시하기 버튼 구현
  src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.tsx
  src/components/TournamentNew/TournamentFlow/TournamentFooter/TournamentFooter.tsx
  src/components/TournamentNew/TournamentResult/TournamentResultFooter/TournamentResultFooter.tsx
  src/components/TournamentNew/TournamentResult/TournamentResultUser/TournamentResultUser.tsx
  src/components/common/Button/Next/BtnNext.tsx
Labels: 기능구현, feat, 토너먼트

#184 [온보딩] step06 퍼널로 복귀 & 로직 완료 & 참여자 뷰 구현
  public/svg/ic_logotype.svg
  public/svg/ic_logotype_final.svg
  src/assets/svg/IcLogotype.tsx
  src/assets/svg/IcLogotypeFinal.tsx
  src/assets/svg/index.ts
  src/components/OnBoardingSteps/Step05/Step05.style.ts
  src/components/OnBoardingSteps/Step05/Step05.tsx
  src/components/OnBoardingSteps/Step06/Step06.tsx
  src/components/OnBoardingSteps/invitationDeadline/InvitationDeadline.style.ts
  src/components/OnBoardingSteps/invitationDeadline/InvitationDeadline.tsx
  src/components/OnBoardingSteps/onboardingHeader/OnBoardingHeader.tsx
  src/components/common/Button/Radio/BtnRadio.tsx
  src/hooks/queries/onboarding/useKakaoShare.tsx
  src/pages/OnBoardingPage.tsx
  src/pages/Participants/ ParticipantsView.tsx
  src/pages/Participants/ParticipantsView.style.ts
  src/router/Router.tsx
Labels: 기능구현, style, 온보딩

#194 [메인] 햄버거 메뉴 헤더 구현
  src/pages/Start/StartHeader/StartHeader.style.ts
  src/pages/Start/StartHeader/StartHeader.tsx
Labels: feat, 시작페이지

#196 [토너먼트] 토너먼트 화면 스타일 리팩토링
  public/svg/trophyNone.svg
  src/assets/svg/TrophyNone.tsx
  src/assets/svg/index.ts
  src/components/TournamentNew/Intro/TournamentContainer.tsx
  src/components/TournamentNew/Intro/TournamentContatiner.style.tsx
  src/components/TournamentNew/Intro/TournamentItemCount/TournamentItemCount.tsx
  src/components/TournamentNew/Intro/TournamentNoneText/TournamentNoneText.style.ts
  src/components/TournamentNew/Intro/TournamentNoneText/TournamentNoneText.tsx
  src/components/TournamentNew/TournamentFlow/TournamentCard/TournamentCard.style.ts
  src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.style.ts
  src/components/TournamentNew/TournamentFlow/TournamentFlowContainer.tsx
  src/components/TournamentNew/TournamentFlow/TournamentTitle/TournamernTitle.style.ts
  src/components/TournamentNew/TournamentRanking/TournamentRanking.style.ts
  src/components/TournamentNew/TournamentRanking/TournamentRanking.tsx
  src/components/TournamentNew/TournamentResult/TournamentResult.sytle.ts
  src/components/TournamentNew/TournamentResult/TournamentResult.tsx
  src/components/TournamentNew/TournamentResult/TournamentTitleSub/TournamnetTitleSub.tsx
  src/components/common/Header.tsx
Labels: feat, refactor, 토너먼트

#212 [마이페이지] 헤더 구현
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPageHeader/MyPageHeader.style.ts
  src/pages/MyPage/MyPageHeader/MyPageHeader.tsx
  src/pages/Start/StartHeader/StartHeader.tsx
Labels: style, 시작페이지

#226 [토너먼트] api access token 없이
  src/components/TournamentNew/TournamentRanking/TournamentRanking.tsx
  src/hooks/queries/tournament/useGetRanking.tsx
Labels: fix, refactor, API

#229 [온보딩] 자잘한 qa들 (미완)
  README.md
  src/components/OnBoardingSteps/Step02/Step02.tsx
  src/components/OnBoardingSteps/Step03/Step03.tsx
  src/components/OnBoardingSteps/Step04/Step04.style.ts
  src/components/OnBoardingSteps/Step04/Step04.tsx
  src/components/OnBoardingSteps/Step04/TimePicker.tsx
  src/components/OnBoardingSteps/Step05/Step05.tsx
  src/components/OnBoardingSteps/Step06/Step06.style.ts
  src/components/OnBoardingSteps/Step06/Step06.tsx
  src/components/common/Button/Radio/BtnRadio.style.ts
  src/components/common/Button/Radio/BtnRadio.tsx
  src/hooks/queries/etc/usePostPresignedUrl.tsx
  src/pages/MyPage/MyPageHeader/MyPageHeader.style.ts
  src/pages/OnBoardingPage.tsx
  src/pages/Participants/ ParticipantsView.tsx
Labels: style, 온보딩

#239 [온보딩] qa 중
  src/components/OnBoardingSteps/Step05/Step05.tsx
  src/components/OnBoardingSteps/Step06/Step06.tsx
  src/hooks/queries/onboarding/useKakaoShare.tsx
  src/router/Router.tsx
Labels: feat, style, 온보딩

#244 [토너먼트] 토너먼트 플로우 라우터 수정
  src/components/TournamentNew/Intro/TournamentContainer.tsx
  src/components/TournamentNew/Intro/TournamentStartText/TournamentStartText.tsx
Labels: fix, 토너먼트
